/**
 * RD-01: builds self-hosted font subsets (OFL 1.1, see ASSETS_LICENSE.md).
 *
 * Google Fonts css2 with `text=` returns a single @font-face containing only
 * the requested glyphs — a few KB instead of full CJK/serif families.
 *
 * Output: public/fonts/*.woff2 + src/styles/fonts.css (@font-face rules).
 * Usage:  npm run assets:fonts
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = (p) => join(root, p);

/* A browser UA is required, otherwise Google serves TTF instead of woff2. */
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const CYRILLIC_LATIN =
  "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ" +
  "абвгдеёжзийклмнопрстуфхцчшщъыьэюя" +
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" +
  "0123456789 .,:;!?—–-«»„“”’'()·+/%№";

const FONTS = [
  {
    cssFamily: "Noto Serif",
    family: "Noto Serif Display",
    weight: 700,
    file: "noto-serif-display-700.woff2",
    text: CYRILLIC_LATIN,
    unicodeRange: null,
  },
  {
    cssFamily: "Noto Sans JP",
    family: "Noto Sans JP Honors",
    weight: 500,
    file: "noto-sans-jp-honors-500.woff2",
    text: "東南西北中發白萬",
    unicodeRange: "U+4E1C, U+5357, U+897F, U+5317, U+4E2D, U+767C, U+767D, U+842C",
  },
];

async function buildFont(font) {
  const url =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(font.cssFamily)}` +
    `:wght@${font.weight}&text=${encodeURIComponent(font.text)}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
    if (!r.ok) throw new Error(`css2 ${font.cssFamily}: HTTP ${r.status}`);
    return r.text();
  });
  // The css2 subset endpoint serves woff2 from a dynamic /l/font?kit= URL.
  const woff2 = css.match(/url\((https:[^)]+)\)\s*format\(['"]woff2['"]\)/);
  if (!woff2) throw new Error(`no woff2 URL in css2 response for ${font.cssFamily}`);
  const bin = Buffer.from(await fetch(woff2[1]).then((r) => r.arrayBuffer()));
  await writeFile(out(`public/fonts/${font.file}`), bin);
  return { ...font, bytes: bin.length };
}

await mkdir(out("public/fonts"), { recursive: true });

const built = [];
for (const font of FONTS) built.push(await buildFont(font));

const faces = built
  .map((f) => {
    const range = f.unicodeRange ? `\n  unicode-range: ${f.unicodeRange};` : "";
    return `@font-face {
  font-family: "${f.family}";
  src: url("/fonts/${f.file}") format("woff2");
  font-weight: ${f.weight};
  font-style: normal;
  font-display: swap;${range}
}`;
  })
  .join("\n\n");

const css = `/*
 * GENERATED by scripts/fonts/build.mjs — do not edit.
 * Self-hosted glyph subsets (SIL OFL 1.1). See ASSETS_LICENSE.md.
 */
${faces}
`;
await writeFile(out("src/styles/fonts.css"), css, "utf8");

let total = 0;
for (const f of built) {
  total += f.bytes;
  console.log(`${f.file}  ${(f.bytes / 1024).toFixed(1)} KB`);
}
console.log(`total ${(total / 1024).toFixed(1)} KB (budget 100 KB)`);
if (total > 100 * 1024) {
  console.warn("WARNING: fonts exceed the 100 KB budget");
  process.exitCode = 1;
}
