/**
 * RD-01: builds the Dorahub "Noir Gold" tile sprite.
 *
 * Source: FluffyStuff/riichi-mahjong-tiles (public domain / CC0), pinned commit.
 * Pipeline: download → recolor to the mahjong-noir palette → prefix internal
 * ids (so symbols can coexist in one sprite) → wrap in <symbol> → SVGO.
 * The tile back is an original Dorahub design (felt + gold), not from upstream.
 *
 * Output: public/tiles.svg (symbol sprite) + public/favicon.svg (東 tile).
 * Usage:  npm run assets:tiles
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { optimize } from "svgo";

const COMMIT = "26e127ba2117f45cdce5ea0225748cc0cfad3169";
const BASE_URL = `https://raw.githubusercontent.com/FluffyStuff/riichi-mahjong-tiles/${COMMIT}/Regular`;

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const out = (p) => join(root, p);

/** [upstream file, sprite id] — ids follow the mjai notation (0 = aka five). */
const FACES = [
  ["Man1", "1m"],
  ["Man2", "2m"],
  ["Man3", "3m"],
  ["Man4", "4m"],
  ["Man5", "5m"],
  ["Man5-Dora", "0m"],
  ["Man6", "6m"],
  ["Man7", "7m"],
  ["Man8", "8m"],
  ["Man9", "9m"],
  ["Pin1", "1p"],
  ["Pin2", "2p"],
  ["Pin3", "3p"],
  ["Pin4", "4p"],
  ["Pin5", "5p"],
  ["Pin5-Dora", "0p"],
  ["Pin6", "6p"],
  ["Pin7", "7p"],
  ["Pin8", "8p"],
  ["Pin9", "9p"],
  ["Sou1", "1s"],
  ["Sou2", "2s"],
  ["Sou3", "3s"],
  ["Sou4", "4s"],
  ["Sou5", "5s"],
  ["Sou5-Dora", "0s"],
  ["Sou6", "6s"],
  ["Sou7", "7s"],
  ["Sou8", "8s"],
  ["Sou9", "9s"],
  ["Ton", "1z"],
  ["Nan", "2z"],
  ["Shaa", "3z"],
  ["Pei", "4z"],
  ["Haku", "5z"],
  ["Hatsu", "6z"],
  ["Chun", "7z"],
  ["Blank", "blank"],
];

/** Upstream palette → mahjong noir (ramp values from src/styles/tokens.css). */
const COLOR_MAP = [
  ["#000000", "#090d18"], // strokes → ink-900
  ["#004900", "#1f7a68"], // bamboo/hatsu green → jade-600
  ["#b93c3c", "#d94e34"], // suit red → coral-500
  ["#d71e1e", "#e65342"], // aka five → vermilion (Plan.md §2.8)
  ["#a53c3c", "#b23a26"], // dark red → coral-600
  ["#ff3737", "#f0725a"], // bright red → coral-400
  ["#3f3fff", "#46539c"], // pin blue → noir indigo
  ["#000037", "#232e4a"], // deep indigo → ink-700
  ["#ff5c00", "#e6b450"], // orange accent → amber-400
  ["#aeffff", "#7fd6c2"], // pale cyan → jade-300
  ["#822600", "#7a5810"], // deep brown-red → amber-700
  ["#666666", "#565d6e"], // neutral grey → ink-550
];

/** Original tile back: night felt, gold double frame and "dora" emblem. */
const BACK_SYMBOL = `<symbol id="tile-back" viewBox="0 0 300 400">
  <defs>
    <linearGradient id="bk-felt" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1a2438"/>
      <stop offset="1" stop-color="#0b111f"/>
    </linearGradient>
    <linearGradient id="bk-gold" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#e6cf9a"/>
      <stop offset=".5" stop-color="#c99a3a"/>
      <stop offset="1" stop-color="#8a6420"/>
    </linearGradient>
    <pattern id="bk-weave" width="16" height="16" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
      <path d="M0 4H16M0 12H16" stroke="#ffffff" stroke-opacity=".05" stroke-width="3"/>
    </pattern>
  </defs>
  <rect x="6" y="6" width="288" height="388" rx="30" fill="url(#bk-felt)" stroke="#05070d" stroke-width="4"/>
  <rect x="6" y="6" width="288" height="388" rx="30" fill="url(#bk-weave)"/>
  <rect x="22" y="22" width="256" height="356" rx="20" fill="none" stroke="url(#bk-gold)" stroke-width="5"/>
  <rect x="34" y="34" width="232" height="332" rx="14" fill="none" stroke="url(#bk-gold)" stroke-width="2" stroke-opacity=".55"/>
  <g fill="none" stroke="url(#bk-gold)">
    <circle cx="150" cy="200" r="72" stroke-width="5"/>
    <path d="M150 150L200 200L150 250L100 200Z" stroke-width="4"/>
    <circle cx="150" cy="200" r="14" fill="url(#bk-gold)" stroke="none"/>
  </g>
  <g fill="url(#bk-gold)">
    <circle cx="150" cy="96" r="7"/>
    <circle cx="150" cy="304" r="7"/>
    <circle cx="54" cy="200" r="7"/>
    <circle cx="246" cy="200" r="7"/>
  </g>
</symbol>`;

const HEADER = `<!-- GENERATED by scripts/tiles/build.mjs — do not edit by hand.
     Source: FluffyStuff/riichi-mahjong-tiles (public domain / CC0), commit ${COMMIT.slice(0, 7)}.
     Recolored to the Dorahub "mahjong noir" palette; tile back is an original design. -->\n`;

async function download(file) {
  const res = await fetch(`${BASE_URL}/${file}.svg`);
  if (!res.ok) throw new Error(`fetch ${file}: HTTP ${res.status}`);
  return res.text();
}

/** Keep only the artwork: strip the <svg> wrapper and all editor metadata. */
function extractInner(svg) {
  const openEnd = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  if (openEnd < 0 || close < 0) throw new Error("not an SVG document");
  return (
    svg
      .slice(openEnd + 1, close)
      .replace(/<!--[\s\S]*?-->/g, "")
      .replace(/<metadata[\s\S]*?<\/metadata>/g, "")
      // Editor-only namespaced elements (inkscape/sodipodi/osb/rdf/…): the
      // rendered geometry stays baked into plain attributes, and namespace
      // prefixes are unbound once the <svg> wrapper is gone.
      .replace(
        /<(([a-z][a-z0-9]*):[a-zA-Z][a-zA-Z0-9._-]*)[^>]*>[\s\S]*?<\/\1>/g,
        "",
      )
      .replace(/<[a-z][a-z0-9]*:[a-zA-Z][a-zA-Z0-9._-]*[^>]*\/>/g, "")
      // Namespaced attributes, keeping xlink:href which the artwork uses.
      .replace(
        /\s(?!xlink:)[a-z][a-z0-9]*:[a-zA-Z][a-zA-Z0-9._-]*="[^"]*"/g,
        "",
      )
      .replace(/<title>[\s\S]*?<\/title>/g, "")
      .replace(/<desc>[\s\S]*?<\/desc>/g, "")
  );
}

function recolor(content) {
  for (const [from, to] of COLOR_MAP) {
    content = content.replace(new RegExp(from, "gi"), to);
  }
  return content;
}

/** Symbols share one document, so every internal id gets a per-tile prefix. */
function prefixIds(content, pfx) {
  const ids = new Set();
  for (const m of content.matchAll(/id="([^"]+)"/g)) ids.add(m[1]);
  for (const id of ids) {
    const esc = id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    content = content
      .replaceAll(`id="${id}"`, `id="${pfx}-${id}"`)
      .replaceAll(`href="#${id}"`, `href="#${pfx}-${id}"`)
      .replace(new RegExp(`url\\(#${esc}\\)`, "g"), `url(#${pfx}-${id})`);
  }
  return content;
}

function svgo(svg) {
  const { data } = optimize(svg, {
    multipass: true,
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            cleanupIds: false, // ids are already namespaced per tile
            // Symbols are referenced from HTML via <use href="/tiles.svg#…">,
            // i.e. externally — SVGO must not treat them as unreferenced
            // defs (removeUselessDefs) or non-rendering elements
            // (removeHiddenElems puts every <symbol> on the removal list).
            removeUselessDefs: false,
            removeHiddenElems: false,
            convertPathData: { floatPrecision: 2 },
          },
        },
      },
    ],
  });
  return data;
}

const report = [];
let tonInner = "";
const symbols = [];

// Front.svg is the shared ivory tile body: every face is layered over it.
const bodyInner = prefixIds(recolor(extractInner(await download("Front"))), "tbody");
const BODY_SYMBOL = `<symbol id="tile-body" viewBox="0 0 300 400">${bodyInner}</symbol>`;
symbols.push(BODY_SYMBOL);

for (const [file, id] of FACES) {
  const raw = await download(file);
  let inner = extractInner(raw);
  inner = recolor(inner);
  inner = prefixIds(inner, `t${id}`);
  if (id === "1z") tonInner = inner;
  symbols.push(
    `<symbol id="tile-${id}" viewBox="0 0 300 400"><use xlink:href="#tile-body"/>${inner}</symbol>`,
  );
  report.push([id, raw.length]);
}
symbols.push(BACK_SYMBOL);

const spriteRaw = `${HEADER}<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n${symbols.join("\n")}\n</svg>\n`;

// Sanity: no editor-namespace markup may survive the cleaning step.
const leftover = spriteRaw.match(
  /<(?!\/)([a-z][a-z0-9]*):[a-zA-Z][a-zA-Z0-9._-]*|\s(?!xlink:|xmlns:)([a-z][a-z0-9]*):[a-zA-Z][a-zA-Z0-9._-]*=/,
);
if (leftover) {
  const idx = spriteRaw.indexOf(leftover[0]);
  console.error("leftover namespaced markup:", leftover[0]);
  console.error(JSON.stringify(spriteRaw.slice(Math.max(0, idx - 200), idx + 300)));
  throw new Error("sprite still contains editor namespaces");
}

if (process.env.SPRITE_DEBUG) {
  await writeFile("/tmp/opencode/sprite-debug.svg", spriteRaw, "utf8");
}

const sprite = svgo(spriteRaw);

for (const [, id] of [...FACES, [null, "back"], [null, "body"]]) {
  if (!sprite.includes(`id="tile-${id}"`)) {
    throw new Error(`symbol tile-${id} lost during optimization`);
  }
}

const favicon = svgo(
  `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 300 400">${BODY_SYMBOL}<use xlink:href="#tile-body"/>${tonInner}</svg>`,
);

await mkdir(out("public"), { recursive: true });
await writeFile(out("public/tiles.svg"), sprite, "utf8");
await writeFile(out("public/favicon.svg"), favicon, "utf8");

const kb = (n) => (n / 1024).toFixed(1);
const gz = gzipSync(sprite).length;
console.log(`tiles: ${FACES.length} faces + back`);
console.log(
  `public/tiles.svg  ${kb(sprite.length)} KB (${kb(gz)} KB gzip, budget 60 KB)`,
);
console.log(`public/favicon.svg ${kb(favicon.length)} KB`);
if (gz > 60 * 1024) {
  console.warn("WARNING: sprite exceeds the 60 KB gzip budget");
  process.exitCode = 1;
}
