/**
 * Tile registry for the Noir Gold sprite (public/tiles.svg, see RD-01).
 * Ids follow the mjai notation: suits 1–9m/p/s, aka fives 0m/0p/0s,
 * honors 1z 東 · 2z 南 · 3z 西 · 4z 北 · 5z 白 · 6z 發 · 7z 中.
 */
export const TILE_IDS = [
  "1m",
  "2m",
  "3m",
  "4m",
  "5m",
  "6m",
  "7m",
  "8m",
  "9m",
  "0m",
  "1p",
  "2p",
  "3p",
  "4p",
  "5p",
  "6p",
  "7p",
  "8p",
  "9p",
  "0p",
  "1s",
  "2s",
  "3s",
  "4s",
  "5s",
  "6s",
  "7s",
  "8s",
  "9s",
  "0s",
  "1z",
  "2z",
  "3z",
  "4z",
  "5z",
  "6z",
  "7z",
  "back",
  "blank",
] as const;

export type TileId = (typeof TILE_IDS)[number];

/** Accessible Russian names — every tile state has a text equivalent. */
export const TILE_LABELS: Record<TileId, string> = {
  "1m": "Ман 1",
  "2m": "Ман 2",
  "3m": "Ман 3",
  "4m": "Ман 4",
  "5m": "Ман 5",
  "6m": "Ман 6",
  "7m": "Ман 7",
  "8m": "Ман 8",
  "9m": "Ман 9",
  "0m": "Ман 5, ака (красная пятёрка)",
  "1p": "Пин 1",
  "2p": "Пин 2",
  "3p": "Пин 3",
  "4p": "Пин 4",
  "5p": "Пин 5",
  "6p": "Пин 6",
  "7p": "Пин 7",
  "8p": "Пин 8",
  "9p": "Пин 9",
  "0p": "Пин 5, ака (красная пятёрка)",
  "1s": "Соу 1",
  "2s": "Соу 2",
  "3s": "Соу 3",
  "4s": "Соу 4",
  "5s": "Соу 5",
  "6s": "Соу 6",
  "7s": "Соу 7",
  "8s": "Соу 8",
  "9s": "Соу 9",
  "0s": "Соу 5, ака (красная пятёрка)",
  "1z": "Восток (тон)",
  "2z": "Юг (нан)",
  "3z": "Запад (ся)",
  "4z": "Север (пей)",
  "5z": "Белый дракон (хаку)",
  "6z": "Зелёный дракон (хацу)",
  "7z": "Красный дракон (чун)",
  back: "Рубашка тайла",
  blank: "Пустой тайл",
};
