spring:
  application:
    name: dorahub
  jackson:
    time-zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:db/migration
    out-of-order: false
  session:
    jdbc:
      cleanup-cron: "0 */10 * * * *"
      initialize-schema: never
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  otlp:
    metrics:
      export:
        enabled: false
  endpoint:
    configprops:
      show-values: never
    env:
      show-values: never
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    export:
      enabled: false
    sampling:
      probability: 0.1

server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        http-only: true
        name: DORAHUB_SESSION
        same-site: lax
      timeout: 12h

dorahub:
  auth:
    external:
      enabled: false
    totp:
      enabled: false
